### ISSUE TITLE
Chapter 4: not-a-sentence

### ISSUE THREAD

**Issue by tballmsft** [amyjko/critically-conscious-computing#10]
> And the computer itself, as always been a project of war and capitalism, a tool for winning World Wars, increasing profits in telecommunications, and accelerating business.

Instead:

> And the computer itself has always been a project of war and capitalism, a tool for winning World Wars, increasing profits in telecommunications, and accelerating business.

**Comment by amyjko** [comment]
Thanks, resolved in 339edb95b2369fa93aa38bb923a37a41a8bb3e5c.
