### ISSUE TITLE
Python examples do not run in Firefox on Mac or Android

### ISSUE THREAD

**Issue by develop4learners** [amyjko/critically-conscious-computing#22]
Hi Amy! 

I'll try to tabulate all the places where the interactive python examples don't run for me. By "don't run" I mean I clicked the play triangle button and nothing happened. To my knowledge, my adblocker is disabled on my Mac. 

If a chapter is skipped in the Table, that means there were no interactive Python examples in that chapter. 

Key:
- "runs fresh then fails" = runs on a fresh page, then fails after navigating the book a while. 
- "fails" = I've never gotten this code to run. It seems that the play arrow/triangle is sometimes black (when the code will run), and then is grayed out for most of the python examples (the code will not run). 

| Chapter | Python   | FF-Mac    | FF-Android |
| -------- | --------  | --------- | -------- |
| 0 (intro) | ex1         | fails         | runs fresh then fails  |
| 3            | ex1         | fails         |  fails |
| 10          | ex1  | fails |  fails |
| 12           | ex1, ex2, ex3, ex4, ex5, ex6, ex7, ex8  | runs fresh then fails, fails, fails, fails, fails, fails, fails, fails | runs fresh then fails, fails, fails, fails, fails, fails, fails, fails |
| 14          | ex1, ex2, ex3  | runs fresh then fails, fails, fails |  runs fresh then fails, fails, fails |
| 16          | ex1  | runs fresh then fails |  runs fresh then fails |
| 17          | ex1, ex2, ex3, ex4  | runs fresh then fails, fails, fails, fails |  runs fresh then fails, fails, fails, fails |
| 18          | ex1  | runs but can't see print output, eventually won't run | same as left  |

**Comment by develop4learners** [comment]
Brendan and Michelle mentioned that their Chrome-Macs have the same behavior

**Comment by amyjko** [comment]
Thank you! I'll find some time to prioritize these fixes.

**Comment by amyjko** [comment]
I diagnosed the problem and deployed a fix over in https://github.com/amyjko/bookish.

In case anyone's curious, I'm using a library that runs Python in the browser and it loads in global variable, like back in the 2000's jQuery era. My code, which loads it on demand, wasn't properly checking to see if it was loaded to determine the enabled state of the play button, and so it would intermittently be enabled depending on whether the Python component loaded before or after the Python engine loaded. If the button rendered after it loaded, it would always be disabled, hence the working once and never again behavior.
