### ISSUE TITLE
Ch 6, mention of Turing being Autistic

### ISSUE THREAD

**Issue by barkh22g** [amyjko/critically-conscious-computing#43]
In Designing Intelligence section:
"Turing, a mathematically gifted White British child of middle class parents — who many suggest might have been a Autistic — found his way to university and research."

I think there is a mistake in referring to him as "a Autistic." In the intro chapter you mention using person-first language throughout the book which this doesn't do. From my experience I also think saying "who might have been autistic" would be fine.

**Comment by amyjko** [comment]
Thanks for reporting this and other typos and corrections! (In this particular case, the "a" was a typo — that usage was definitely not intentional).
