### ISSUE TITLE
funding of code.org and Brad Smith

### ISSUE THREAD

**Issue by tballmsft** [amyjko/critically-conscious-computing#7]
> Philanthropists like Brad Smith of Microsoft funded not-for-profits like Code.org, 

My understanding is that Brad Smith was instrumental in getting Microsoft to be a major funder of code.org. Please see: https://code.org/about/donors. I do not see Brad Smith listed here, so I am not sure that the above statement is accurate.

**Comment by amyjko** [comment]
That's a good clarification; it wasn't Brad, but Microsoft.
